In [1]:
import numpy as np

arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:


arr2d = np.array([[1, 2, 3],
                   [4, 5, 6]])

print(arr2d)
print(type(arr2d))
print(arr2d.ndim)


[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
2


In [10]:
arr3d = np.array([
    [[1, 2, 3]],
    [[4, 5, 6]],
    [[7, 8, 9]]
])

print(arr3d)
print(type(arr3d))
print(arr3d.ndim)


[[[1 2 3]]

 [[4 5 6]]

 [[7 8 9]]]
<class 'numpy.ndarray'>
3


In [9]:
ar4= np.array([1,2,3,4], ndmin=5)
print(ar4)
print(ar4.ndim)

[[[[[1 2 3 4]]]]]
5


In [11]:
a = np.array([[1, 2, 3], [4, 5, 6]])

a=a.reshape(3,2)

print(a)

[[1 2]
 [3 4]
 [5 6]]


In [6]:
import numpy as np

a = np.array([10, 20, 30, 40, 50, 60])

print(a[1:4])

b = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])


print(b[0:3])

print(b[0:2,0:2])


[20 30 40]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]]


In [13]:
import numpy as np

a = np.arange(1, 16)
print(arr)
third  = a[2]
fifth  = a[4]
eighth = a[7]

print(third, fifth, eighth)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
3 5 8


In [15]:
import numpy as np

arr = np.arange(1, 11).reshape(2, 5)
print(arr)
import numpy as np

arr = np.arange(1, 11).reshape(2, 5)

print(arr)
print(arr[1, 0])   
print(arr[0, 0])  
print(arr[-1, -1])


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
6
1
10


In [18]:
import numpy as np

arr = np.arange(1, 13).reshape(2, 2, 3)

print("3D Array:", arr)
print("Shape:", arr.shape)
print("Dimensions:", arr.ndim)

print("All elements:", arr.flatten())
print(arr[0,0,0])
print(arr[0,0,1])
print(arr[0,0,2])
print(arr[0,1,0])
print(arr[0,1,1])
print(arr[0,1,2])
print(arr[1,0,0])
print(arr[1,0,1])
print(arr[1,0,2])
print(arr[1,1,0])
print(arr[1,1,1])
print(arr[1,1,2])



3D Array: [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Shape: (2, 2, 3)
Dimensions: 3
All elements: [ 1  2  3  4  5  6  7  8  9 10 11 12]
1
2
3
4
5
6
7
8
9
10
11
12


In [ ]:
a=np.linspace(5,10,15)
print(a)

[ 5.          5.35714286  5.71428571  6.07142857  6.42857143  6.78571429
  7.14285714  7.5         7.85714286  8.21428571  8.57142857  8.92857143
  9.28571429  9.64285714 10.        ]


In [ ]:
a = np.array([5, 2, 9, 1, 7, 6, 3, 8, 4, 10])

print("Array:", a)
print("Maximum:", a.max())
print("Minimum:", a.min())
print("Sum of elements:", a.sum())
print("Sum of 2 elements:", a[1] + a[4])

#min max sum only a.

Array: [ 5  2  9  1  7  6  3  8  4 10]
Maximum: 10
Minimum: 1
Sum of elements: 55
Sum of 2 elements: 9


In [33]:
import numpy as np

a = np.arange(1, 7).reshape(2, 3)

print("2D Array:", a)
print("Max of each row:", a.max(axis=1))
print("Min of each column:", a.min(axis=0))
print("Sum of each row:", a.sum(axis=1))


2D Array: [[1 2 3]
 [4 5 6]]
Max of each row: [3 6]
Min of each column: [1 2 3]
Sum of each row: [ 6 15]


In [ ]:
a=np.array([[16,9,36],[9,4,64]])
print(np.sqrt(a))
 #np needs for sqrt

[[4. 3. 6.]
 [3. 2. 8.]]


In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[6, 5, 4], [3, 2, 1]])

print("a:", a)
print("b:", b)
print("a+b:", a + b)
print("a-b:", a - b)
print("a*b:", a * b)
print("a/b:", a / b)
print("Horizontal concat\n:", np.hstack((a, b)))
print("Vertical concat\n:", np.vstack((a, b)))
#np needs for stack

a: [[1 2 3]
 [4 5 6]]
b: [[6 5 4]
 [3 2 1]]
a+b: [[7 7 7]
 [7 7 7]]
a-b: [[-5 -3 -1]
 [ 1  3  5]]
a*b: [[ 6 10 12]
 [12 10  6]]
a/b: [[0.16666667 0.4        0.75      ]
 [1.33333333 2.5        6.        ]]
Horizontal concat
: [[1 2 3 6 5 4]
 [4 5 6 3 2 1]]
Vertical concat
: [[1 2 3]
 [4 5 6]
 [6 5 4]
 [3 2 1]]
