In [2]:
import numpy as np

a=np.empty((4,3),dtype=int)
print(a)
v=np.zeros((2,3),dtype=int)
print(v)
c=np.ones((3,3), dtype=int,order="C")
print(c)
c=np.ones((3,3), dtype=int)
print(c)



[[               -1 32651591227605107 27866160140451941]
 [31244194868494433 29555310643380340 32651234743943278]
 [28710585070059624  9007633053515881 27866456493391987]
 [28429423626027113               100 32767020234440704]]
[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [3]:
l = [1, 2, 3, 4, 5]

a = np.asarray(l)



print("asarray:", a)


asarray: [1 2 3 4 5]


In [4]:
a = [1, 2, 3, 4, 5]
i=iter(a)
x= np.fromiter(i, dtype=int)

print(x)

[1 2 3 4 5]


In [5]:
a=np.arange(1,10,1,float)
print(a)
b=np.linspace(1,6,4)
print(b)
c=np.logspace(1,10,num=5,base=2,endpoint=True)
print(c)

[1. 2. 3. 4. 5. 6. 7. 8. 9.]
[1.         2.66666667 4.33333333 6.        ]
[   2.            9.51365692   45.254834    215.2694823  1024.        ]


In [6]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([10, 20, 30])


print("addition:", a + b)


addition: [[11 22 33]
 [14 25 36]]


In [7]:
a=np.arange(1,13,1).reshape(3,4)
print(a)
for f in np.nditer(a):
 
 print(f,end=" ")
print()

g=a.T
print(g)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
1 2 3 4 5 6 7 8 9 10 11 12 
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [8]:
a=np.arange(1,13,1).reshape(3,4)
print(a)

g=a.T
print(g)

for f in np.nditer(g):
 print(f,end=" ")
print()

f= g.copy(order="C")
print(f)

for m in np.nditer(f):
    print(m)
    
k=f.copy(order="F")
print(k)

for n in np.nditer(k):
 print(n)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
1 2 3 4 5 6 7 8 9 10 11 12 
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
1
5
9
2
6
10
3
7
11
4
8
12
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
1
2
3
4
5
6
7
8
9
10
11
12
