In [1]:
 import  numpy  as  np 
 import  numpy.matlib 
 # --- matlib.identity --- 
 print(np.matlib.identity(  2  ))  # Example 1: 2x2 Identity 
 print(np.matlib.identity(  5  ))  # Example 2: 5x5 Identity 
 print(np.matlib.identity(  3  , dtype=  int  ))  # Example  3: Integer type identity 
 # --- matlib.rand --- 
 print(np.matlib.rand( 3 , 3  ))  # Example 1: 3x3 Random  floats 
 print(np.matlib.rand( 1 , 5  ))  # Example 2: 1 row, 5  cols 
 print(np.matlib.rand( 2 ,  2  ) *  10  )  # Example 3: Random  values up to 10 
 # --- matlib.empty --- 
 print(np.matlib.empty((  2  ,  2  )))  # Example 1: Fast allocation 
 print(np.matlib.empty((  3  ,  1  )))  # Example 2: 3x1 empty  matrix 

[[1. 0.]
 [0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[0.87838989 0.53538283 0.87663075]
 [0.97841055 0.70287303 0.95770051]
 [0.23280258 0.20332482 0.79137797]]
[[0.87409979 0.57792078 0.35194521 0.97751584 0.84787257]]
[[5.74809966 2.12212355]
 [1.10992187 4.19206659]]
[[5.74809966 2.12212355]
 [1.10992187 4.19206659]]
[[5.e-324]
 [0.e+000]
 [0.e+000]]
