In [ ]:
import numpy as np
a=np.array([10,20,30])
print(np.sin(a*np.pi/180))
print(np.cos(a*np.pi/180))
print(np.tan(a*np.pi/180))

[0.17364818 0.34202014 0.5       ]
[0.98480775 0.93969262 0.8660254 ]
[0.17632698 0.36397023 0.57735027]


In [7]:
a=np.array([10,20,30])
sv=np.sin(a*np.pi/180)
print(sv)
cosec=np.arcsin(sv)
print(cosec)
dg=np.degrees(cosec)
print(dg)

cosv=np.cos(a*np.pi/180)
print(cosv)
sec=np.arccos(cosv)
print(sec)
dg2=np.degrees(sec)
print(dg2)


tn=np.tan(a*np.pi/180)
print(tn)
cot=np.arctan(tn)
print(cot)
dg3=np.degrees(cot)
print(dg3)

[0.17364818 0.34202014 0.5       ]
[0.17453293 0.34906585 0.52359878]
[10. 20. 30.]
[0.98480775 0.93969262 0.8660254 ]
[0.17453293 0.34906585 0.52359878]
[10. 20. 30.]
[0.17632698 0.36397023 0.57735027]
[0.17453293 0.34906585 0.52359878]
[10. 20. 30.]


In [ ]:
import numpy as np

b = np.array([1.2, 2.5, 3.7, -1.4, -2.6])

v=np.around(b)

w=np.floor(b)

p=np.ceil(b)

print(b)

print(v)

print(w)
 
print(p)

[ 1.2  2.5  3.7 -1.4 -2.6]
[ 1.  2.  4. -1. -3.]
[ 1.  2.  3. -2. -3.]
[ 2.  3.  4. -1. -2.]
