In [3]:
import numpy as np
import numpy.matlib

print(np.matlib.empty((2,3)))
print(np.matlib.zeros((2,3)))
print(np.matlib.ones((2,3)))

[[9.34577196e-307 9.34598246e-307 1.60218491e-306]
 [1.69119873e-306 1.24611673e-306 1.05699581e-307]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
import numpy.matlib

# n is row, M is col, k is ind of diag
print(numpy.matlib.eye(n=3,M=3,k=0,dtype=int))

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
print(numpy.matlib.identity(3,dtype=int))
print(numpy.matlib.rand(3,3))  #btw 0 and 1 onlyy

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[0.77279857 0.55166961 0.18799151]
 [0.24410844 0.68864337 0.53627848]
 [0.33264578 0.04093093 0.38446322]]
