In [51]:
#amx amin
import numpy as np

a=np.array([[4,3,5,2],[8,6,7,4],[1,11,5,8]])
print(a)

print(np.amax(a))

print(np.amin(a))

print(np.amax(a,axis=1))

print(np.amin(a,axis=1))

print(np.amax(a,axis=0))

print(np.amin(a,axis=0))

print(np.amax(a,axis=1))


[[ 4  3  5  2]
 [ 8  6  7  4]
 [ 1 11  5  8]]
11
1
[ 5  8 11]
[2 4 1]
[ 8 11  7  8]
[1 3 5 2]
[ 5  8 11]


In [ ]:
print(a)
#ptp means last-1st
print(np.ptp(a,axis=1))
print(np.ptp(a,axis=0))


In [48]:
b=([20,40,30,10])
print(b)

print(np.percentile(b,40))




[20, 40, 30, 10]
22.0


In [14]:
#med mean avg

print(a)

print(np.median(a,0))
print(np.mean(a,0))
print(np.average(a,1))


[[ 3  4  5]
 [ 5  6  7]
 [ 1 11  5]]
[3. 6. 5.]
[3.         7.         5.66666667]
[4.         6.         5.66666667]


In [ ]:
#sort
print(a)
print(np.sort(a))
print(np.sort(a,0))
print(np.sort(a,1))

[[ 4  3  5]
 [ 8  6  7]
 [ 1 11  5]]
[[ 3  4  5]
 [ 6  7  8]
 [ 1  5 11]]
[[ 1  3  5]
 [ 4  6  5]
 [ 8 11  7]]
[[ 3  4  5]
 [ 6  7  8]
 [ 1  5 11]]


In [ ]:
#important
import numpy as np

d = np.dtype([("name", "S10"), ("marks", int)])

ar = np.array([("mukesh", 200), ("jay", 330)], dtype=d)

print(np.sort(ar, order="name"))


[(b'jay', 330) (b'mukesh', 200)]


In [5]:
import numpy as np
arglist=np.array([30,20,10,40])
print(arglist)

sorted= np.argsort(arglist)
print(sorted)



for i in sorted:
    print(arglist[i])
    

[30 20 10 40]
[2 1 0 3]
10
20
30
40


In [35]:
print(b)
st=(["a","b","c","d"])
print(st)

lex=np.lexsort((b,st))

print(lex)
for i in lex:
    print(b[i],st[i])



[20, 40, 30, 10]
['a', 'b', 'c', 'd']
[0 1 2 3]
20 a
40 b
30 c
10 d


In [38]:
nz=np.array([30,20,10])
print(nz)

print(nz.nonzero())

[30 20 10]
(array([0, 1, 2]),)


In [41]:
print(nz)
print(np.where(nz>10))

[30 20 10]
(array([0, 1]),)
